/*	Create a view in the view designer, tidy up its SQL and use it to select data.

*/

SELECT * FROM TBLCATEGORY;

SELECT * FROM TBLEVENT;

CREATE VIEW EventsByCategory 
AS
SELECT TOP 100 PERCENT
       C.CATEGORYNAME AS 'CATEGORY',
	   COUNT(E.EVENTNAME) AS 'WHAT'
	   FROM TBLCATEGORY C JOIN TBLEVENT E
	   ON C.CATEGORYID = E.CATEGORYID
	   GROUP BY C.CATEGORYNAME
	   ORDER BY 'WHAT' DESC;

SELECT * FROM EventsByCategory;

ALTER VIEW EventsByCategory 
AS
SELECT TOP 100 PERCENT
       C.CATEGORYNAME AS 'CATEGORY',
	   COUNT(E.EVENTNAME) AS 'WHAT'
	   FROM TBLCATEGORY C JOIN TBLEVENT E
	   ON C.CATEGORYID = E.CATEGORYID
	   GROUP BY C.CATEGORYNAME
	   ORDER BY 'WHAT' ASC;

SELECT * FROM EventsByCategory WHERE WHAT > 50;




