/*Write a view to combine tables, then use this as a basis for a grouping query.

Write the script to generate a view called vwEverything (based on the tblCategory, 
tblEvent, tblCountry and tblContinent tables) to show this data:

*/

SELECT * FROM TBLCATEGORY;

SELECT * FROM TBLCONTINENT;

SELECT * FROM TBLCOUNTRY;

SELECT * FROM TBLEVENT;

CREATE VIEW VWEVERYTHING
AS
SELECT CT.CATEGORYNAME AS 'CATEGORY',
       CN.CONTINENTNAME AS 'CONTINENT',
	   CY.COUNTRYNAME AS 'COUNTRY',
	   E.EVENTNAME,
	   E.EVENTDATE
	   FROM TBLCATEGORY CT JOIN TBLEVENT E 
	   ON CT.CATEGORYID = E.CATEGORYID
	   JOIN TBLCOUNTRY CY 
	   ON CY.COUNTRYID = E.COUNTRYID
	   JOIN TBLCONTINENT CN
	   ON CY.CONTINENTID = CN.CONTINENTID

SELECT CATEGORY,COUNT(EVENTNAME) AS 'NUMBEREVENTS' FROM VWEVERYTHING WHERE CONTINENT = 'AFRICA' GROUP BY CATEGORY ORDER BY NUMBEREVENTS DESC;