/*	Script a view in a query, then use the view designer to edit it.

*/

SELECT * FROM TBLEPISODE;

CREATE VIEW VWSERIESONE 
AS
SELECT TITLE,
       SERIESNUMBER,
	   EPISODENUMBER
	   FROM TBLEPISODE

SELECT * FROM VWSERIESONE;

ALTER VIEW VWSERIESONE 
AS
SELECT TITLE,
       SERIESNUMBER,
	   EPISODENUMBER
	   FROM TBLEPISODE
	   WHERE SERIESNUMBER = 1

SELECT * FROM VWSERIESONE;

ALTER VIEW VWSERIESONE 
AS
SELECT TITLE,
       SERIESNUMBER,
	   EPISODENUMBER
	   FROM TBLEPISODE
	   WHERE SERIESNUMBER = 2

SELECT * FROM VWSERIESONE;
