/*Use IsNull, Coalesce and/or CASE WHEN to replace nulls with values.

The tblContinent table lists out the world's continents, but there are gaps:


*/

SELECT * FROM TBLCONTINENT;

SELECT CONTINENTNAME,
       SUMMARY,
	   ISNULL(SUMMARY,'NO SUMMARY') AS 'USING ISNULL',
	   COALESCE(SUMMARY,'NO SUMMARY') AS 'USING COALESCE',
	   CASE WHEN SUMMARY = 'BIG' THEN 'BIG'
	        WHEN SUMMARY = 'BIGGISH' THEN 'BIGGISH'
			WHEN SUMMARY = 'HOME' THEN 'HOME'
			WHEN SUMMARY = 'LOTS OF TREES' THEN 'LOTS OF TREES'
			WHEN SUMMARY = 'FULL OF PENGUINS' THEN 'FULL OF PENGUINS'
			ELSE 'NO SUMMARY'
	   END AS 'USING CASE'
	   FROM TBLCONTINENT;

--------------------------------- OR ---------------------------------------------

SELECT CONTINENTNAME,
       SUMMARY,
	   ISNULL(SUMMARY,'NO SUMMARY') AS 'USING ISNULL',
	   COALESCE(SUMMARY,'NO SUMMARY') AS 'USING COALESCE',
	   CASE WHEN SUMMARY IS NULL THEN 'NO SUMMARY'
	   ELSE SUMMARY
	   END 'USING CASE'
	   FROM TBLCONTINENT;

--------------------------------- OR ---------------------------------------------

SELECT CONTINENTNAME,
       SUMMARY,
	   ISNULL(SUMMARY,'NO SUMMARY') AS 'USING ISNULL',
	   COALESCE(SUMMARY,'NO SUMMARY') AS 'USING COALESCE',
	   CASE WHEN SUMMARY IN('BIG','BIGGISH','HOME','LOTS OF TREES','FULL OF PENGUINS') THEN SUMMARY
	   ELSE 'NO SUMMARY'
	   END AS 'USING CASE'
	   FROM TBLCONTINENT;