/*Use an inner join to link two tables together in a query.

*/

SELECT * FROM TBLAUTHOR;

SELECT * FROM TBLEPISODE;

SELECT T1.AUTHORNAME,
       T2.TITLE,
	   T2.EPISODETYPE
	   FROM TBLAUTHOR T1 JOIN
	   TBLEPISODE T2 
	   ON T1.AUTHORID = T2.AUTHORID 
	   WHERE T2.EPISODETYPE LIKE '%SPECIAL%'
	   ORDER BY T2.TITLE;
