/*Use SELECT, FROM, WHERE, GROUP BY, HAVING and ORDER BY to list non-European busy countries.

Create a query listing out for each continent and country the number of events taking place therein.

Now change your query so that it omits events taking place in the continent of Europe:

Finally, change your query so that it only shows countries having 5 or more events:
*/

SELECT * FROM TBLCONTINENT;

SELECT * FROM TBLCOUNTRY;

SELECT * FROM TBLEVENT;

SELECT CN.CONTINENTNAME AS 'CONTINENT',
       CO.COUNTRYNAME AS 'COUNTRY',
	   COUNT(EVENTID) AS 'NUMBER OF EVENTS'
	   FROM TBLCONTINENT CN JOIN TBLCOUNTRY CO
	   ON CN.CONTINENTID = CO.CONTINENTID
	   JOIN TBLEVENT E ON E.COUNTRYID = CO.COUNTRYID
	   GROUP BY CN.CONTINENTNAME,
	   CO.COUNTRYNAME
	   ORDER BY COUNTRY;

SELECT CN.CONTINENTNAME AS 'CONTINENT',
       CO.COUNTRYNAME AS 'COUNTRY',
	   COUNT(EVENTID) AS 'NUMBER OF EVENTS'
	   FROM TBLCONTINENT CN JOIN TBLCOUNTRY CO
	   ON CN.CONTINENTID = CO.CONTINENTID
	   JOIN TBLEVENT E ON E.COUNTRYID = CO.COUNTRYID
	   WHERE CN.CONTINENTNAME <> 'EUROPE'
	   GROUP BY CN.CONTINENTNAME,
	   CO.COUNTRYNAME
	   ORDER BY COUNTRY;


SELECT CN.CONTINENTNAME AS 'CONTINENT',
       CO.COUNTRYNAME AS 'COUNTRY',
	   COUNT(EVENTID) AS 'NUMBER OF EVENTS'
	   FROM TBLCONTINENT CN JOIN TBLCOUNTRY CO
	   ON CN.CONTINENTID = CO.CONTINENTID
	   JOIN TBLEVENT E ON E.COUNTRYID = CO.COUNTRYID
	   WHERE CN.CONTINENTNAME <> 'EUROPE'
	   GROUP BY CN.CONTINENTNAME,
	   CO.COUNTRYNAME
	   HAVING COUNT(EVENTID) >= 5
	   ORDER BY COUNTRY;
       