-- WRITE AN SQL QUERY TO FIND A MANAGER NAME WHO MANAGE MORE THEN 4 EMPLOYEES.

CREATE TABLE Employee3 (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    department VARCHAR(50),
    managerId INT
);

INSERT INTO Employee3 (id, name, department, managerId) VALUES 
(1, 'John', 'HR', NULL),
(2, 'Bob', 'HR', 1),
(3, 'Olivia', 'HR', 1),
(4, 'Emma', 'Finance', NULL),
(5, 'Sophia', 'HR', 1),
(6, 'Mason', 'Finance', 4),
(7, 'Ethan', 'HR', 1),
(8, 'Ava', 'HR', 1),
(9, 'Lucas', 'HR', 1),
(10, 'Isabella', 'Finance', 4),
(11, 'Harper', 'Finance', 4),
(12, 'Hemla', 'HR', 3),
(13, 'Aisha', 'HR', 2),
(14, 'Himani', 'HR', 2),
(15, 'Lily', 'HR', 2);

SELECT * FROM EMPLOYEE3;

SELECT * FROM EMPLOYEE3 E1 INNER JOIN EMPLOYEE3 E2
ON E1.ID = E2.MANAGERID;

WITH CTE AS(
SELECT E1.*,COUNT(E2.MANAGERID) OVER(PARTITION BY E2.MANAGERID ORDER BY E2.MANAGERID) AS CNT FROM EMPLOYEE3 E1 INNER JOIN EMPLOYEE3 E2
ON E1.ID = E2.MANAGERID
)
SELECT * FROM CTE WHERE CNT >= 5;

WITH CTE AS(
SELECT E1.*,COUNT(E2.MANAGERID) OVER(PARTITION BY E2.MANAGERID ORDER BY E2.MANAGERID) AS CNT FROM EMPLOYEE3 E1 INNER JOIN EMPLOYEE3 E2
ON E1.ID = E2.MANAGERID
)
SELECT NAME AS MANAGER_NAME,COUNT(*) FROM CTE WHERE CNT >= 5 GROUP BY NAME;